name: tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
        python-version: [3.8, 3.9, 3.10]
    steps:
      - run: |
          pwd
          python -m unittest test_example
